---
resources:
  - name: angular-concourse-ci
    type: git
    source:
      uri: https://github.com/ankit68543/angular-concourse-ci.git

jobs:
  - name: build-and-test
    plan:
      - get: angular-concourse-ci
        trigger: true
      - task: install-dependencies
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: node, tag: "14" }
          inputs:
            - name: angular-concourse-ci
          run:
            path: /bin/sh
            args:
              - -exc
              - |
                cd angular-concourse-ci
                npm install
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: node, tag: "14" }
          inputs:
            - name: angular-concourse-ci
          run:
            path: /bin/sh
            args:
              - -exc
              - |
                npm install -g @angular/cli@16.0.6
                cd angular-concourse-ci
                npm run test
      - task: build-angular-app
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: node, tag: "14" }
          inputs:
            - name: angular-concourse-ci
          run:
            path: /bin/sh
            args:
              - -exc
              - |
                cd angular-concourse-ci
                npm run build
      - task: deploy-to-local
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: alpine, tag: "latest" }
          inputs:
            - name: angular-concourse-ci
          run:
            path: /bin/sh
            args:
              - -exc
              - |
                apk add rsync
                cd angular-concourse-ci/dist
                rsync -avz . D:\Deployment